# 256 Tokens per KV Chunk
chunk_size: 256

# CPU offloading configurations
# local_cpu: true
# max_local_cpu_size: 5.0 # 5GB CPU memory limit

# Enable Disk backend
local_disk: "file:///home/ubuntu/lmcache_disk"
# 5GB of Disk memory
max_local_disk_size: 5.0
